# .gemini/config.yaml copied from https://github.com/google-gemini/gemini-cli/blob/main/.gemini/config.yaml
have_fun: true
code_review:
  #disable: false
  comment_severity_threshold: HIGH
  max_review_comments: -1
  pull_request_opened:
    help: true
    summary: true
    code_review: true
ignore_patterns: []
